FROM archlinux:latest
RUN pacman -Syyu --noconfirm
RUN pacman -S --noconfirm bc curl findutils diffutils less shadow ncurses pinentry sudo wget procps-ng util-linux vte3 lsof time gnupg vulkan-intel vulkan-radeon
