FROM rockylinux:8
RUN dnf install -y bc curl diffutils findutils less ncurses passwd pinentry procps-ng shadow-utils sudo util-linux vte-profile wget dnf-plugins-core lsof time \
mesa-dri-drivers mesa-vulkan-drivers vulkan-loader