FROM ghcr.io/bigpod98/bigpodsb/distroboxes/opensusebased/standardenv:latest
RUN zypper install -n bash fish
RUN sudo ln -s /usr/bin/distrobox-host-exec /usr/bin/flatpak
RUN sudo ln -s /usr/bin/distrobox-host-exec /usr/bin/podman
