FROM ghcr.io/bigpod98/bigpodsb/distroboxes/fedorabased/standardenv:latest
RUN dnf install -y bash fish
RUN sudo ln -s /usr/bin/distrobox-host-exec /usr/bin/flatpak
RUN sudo ln -s /usr/bin/distrobox-host-exec /usr/bin/podman
