FROM ghcr.io/bigpod98/bigpodsb/distroboxes/debianbased/baseenv:latest
RUN apt install -y bash fish
RUN sudo ln -s /usr/bin/distrobox-host-exec /usr/bin/flatpak
RUN sudo ln -s /usr/bin/distrobox-host-exec /usr/bin/podman
