FROM opensuse/tumbleweed:latest
RUN zypper -n install bc curl wget diffutils findutils less ncurses shadow pinentry sudo procps util-linux Mesa Mesa-dri Mesa-gallium Mesa-libEGL1 Mesa-libGL1 \
Mesa-libglapi0 adwaita-icon-theme cups-config fontconfig gdk-pixbuf-loader-rsvg gdk-pixbuf-query-loaders gio-branding-openSUSE glib2-tools gstreamer \
gstreamer-plugins-base gtk3-data gtk3-schema gtk3-tools gtk4-schema gtk4-tools hicolor-icon-theme libLLVM16 libX11-6 libX11-data libX11-xcb1 libXau6 libXcomposite1 \
libXcursor1 libXdamage1 libXext6 libXfixes3 libXft2 libXi6 libXinerama1 libXrandr2 libXrender1 libXv1 libXxf86vm1 libasound2 libatk-1_0-0 libatk-bridge-2_0-0 libatspi0 \
libavahi-client3 libavahi-common3 libcairo-gobject2 libcairo-script-interpreter2 libcairo2 libcdda_interface0 libcdda_paranoia0 libcloudproviders0 libcolord2 libcups2 \
libdatrie1 libdrm2 libdrm_amdgpu1 libdrm_intel1 libdrm_nouveau2 libdrm_radeon1 libdw1 libedit0 libelf1 libepoxy0 libfontconfig1 libfreetype6 libfribidi0 libgbm1 \
libgdk_pixbuf-2_0-0 libgio-2_0-0 libglvnd libgmodule-2_0-0 libgnutls30 libgnutls30-hmac libgobject-2_0-0 libgraphene-1_0-0 libgraphite2-3 libgstallocators-1_0-0 \
libgstapp-1_0-0 libgstaudio-1_0-0 libgstgl-1_0-0 libgstpbutils-1_0-0 libgstplay-1_0-0 libgstplayer-1_0-0 libgstreamer-1_0-0 libgstriff-1_0-0 libgsttag-1_0-0 \
libgstvideo-1_0-0 libgtk-3-0 libgtk-4-1 libgudev-1_0-0 libharfbuzz0 libhogweed6 libjbig2 libjitterentropy3 libjpeg8 libjson-glib-1_0-0 liblcms2-2 libnettle8 libogg0 \
libopus0 liborc-0_4-0 libpango-1_0-0 libpciaccess0 libpixman-1-0 libpng16-16 librsvg-2-2 libthai-data libthai0 libtheoradec1 libtheoraenc1 libtiff6 \
libtracker-sparql-3_0-0 libunwind8 libvisual-0_4-0 libvorbis0 libvorbisenc2 libvte-2_91-0 libwayland-client0 libwayland-cursor0 libwayland-egl1 libwayland-server0 \
libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0 libxcb-present0 libxcb-randr0 libxcb-render0 libxcb-shm0 libxcb-sync1 libxcb-xfixes0 libxcb1 libxkbcommon0 libxshmfence1 lsof \
shared-mime-info system-user-lp time util-linux-systemd xkeyboard-config Mesa-vulkan-device-select libvulkan1 libvulkan_radeon
