FROM fedora-minimal:38
RUN dnf5 install -y bc curl diffutils findutils less ncurses passwd pinentry procps-ng shadow-utils sudo util-linux vte-profile wget util-linux-user time lsof mesa-dri-drivers mesa-vulkan-drivers 
