FROM ghcr.io/bigpod98/bigpodsb/distroboxes/alpinebased/baseenv:latest
RUN apk add bash fish
RUN sudo ln -s /usr/bin/distrobox-host-exec /usr/bin/flatpak
RUN sudo ln -s /usr/bin/distrobox-host-exec /usr/bin/podman
