FROM ghcr.io/bigpod98/bigpodsb/distroboxes/debianbased/baseenv:latest
RUN apt autoremove -y vim vim-runtime vim-tiny vim-common 
RUN apt install -y --no-install-recommends nano tar zip unzip jq fish direnv 