FROM ghcr.io/bigpod98/bigpodsb/distroboxes/rockylinuxbased/baseenv:latest
RUN dnf install -y bash
RUN sudo ln -s /usr/bin/distrobox-host-exec /usr/bin/flatpak
RUN sudo ln -s /usr/bin/distrobox-host-exec /usr/bin/podman
