FROM ubuntu:lunar
RUN apt update && apt upgrade -y
RUN echo "test"
RUN apt install -y --no-install-recommends bc curl diffutils findutils less passwd pinentry-tty sudo util-linux wget ncurses-base ncurses-bin 